<?php
/*
 * Settings metadata file
 */
return [
  'eventsextras_roles' => [
    'name' => 'eventsextras_roles',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Default Role'),
    'help_text' => '',
    'section' => 'front_page',
  ],
  'eventsextras_participant_listing' => [
    'name' => 'eventsextras_participant_listing',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => FALSE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Participant listing'),
    'help_text' => '',
    'section' => 'front_page',
  ],
  'eventsextras_event_summary' => [
    'name' => 'eventsextras_event_summary',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Event Summary'),
    'help_text' => '',
    'section' => 'front_page',
  ],
  'eventsextras_completed_description' => [
    'name' => 'eventsExtrasCompleteDescription',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Complete Description'),
    'help_text' => '',
    'section' => 'front_page',
  ],
  'eventsextras_include_map_event_location' => [
    'name' => 'eventsextras_include_map_event_location',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Include Map to Event Location'),
    'help_text' => '',
    'section' => 'front_page',
  ],
  'eventsextras_public_event' => [
    'name' => 'eventsextras_public_event',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Public Event'),
    'help_text' => '',
    'section' => 'front_page',
  ],
  'eventsextras_currency' => [
    'name' => 'eventsextras_currency',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Currency'),
    'help_text' => '',
    'section' => 'fee',
  ],
  'eventsextras_enable_pay_later_option' => [
    'name' => 'eventsextras_enable_pay_later_option',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Enable pay later option'),
    'help_text' => '',
    'section' => 'fee',
  ],
  'eventsextras_payment_processor_selection' => [
    'name' => 'eventsextras_payment_processor_selection',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Payment Processor Selection'),
    'help_text' => '',
    'section' => 'fee',
  ],
  'eventsextras_pending_participant_expiration' => [
    'name' => 'eventsextras_pending_participant_expiration',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Pending Participant Expiration'),
    'help_text' => '',
    'section' => 'online_registration',
  ],
  'eventsextras_allow_self_service' => [
    'name' => 'eventsextras_allow_self_service',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Allow self-service cancellation or transfer?'),
    'help_text' => '',
    'section' => 'online_registration',
  ],
  'eventsextras_register_multiple_participants' => [
    'name' => 'eventsextras_register_multiple_participants',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => TRUE,
    'html_type' => 'radio',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Show/Hide Register multiple participants?'),
    'help_text' => '',
    'section' => 'online_registration',
  ],
];