<?php

use CRM_EventsExtras_SettingsManager as SettingsManager;

/*
 * Settings metadata file for storing default value when user is selected to hide
 */
return [
  'eventsextras_roles_default' => [
    'name' => 'eventsextras_roles_default',
    'title' => ts('Set Default Setting of Default Role'),
    'type' => 'Integer',
    'quick_form_type' => 'Select',
    'default' => '',
    'html_type' => 'select',
    'pseudoconstant' => [
      'optionGroupName' => 'participant_role',
    ],
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => '',
    'is_help' => TRUE,
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_INFO,
      'parent_setting' => SettingsManager::SETTING_FIELDS['ROLES'],
      'event_form_element_name' => 'default_role_id',
      'class' => 'crm-select2',
      'placeholder' => ts('- Select -'),
    ],
  ],
  'eventsextras_participant_listing_default' => [
    'name' => 'eventsextras_participant_listing_default',
    'title' => ts('Set Default Setting of Participant Listing'),
    'type' => 'Integer',
    'quick_form_type' => 'Select',
    'default' => '',
    'html_type' => 'select',
    'pseudoconstant' => [
      'optionGroupName' => 'participant_listing',
    ],
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => '',
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_INFO,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PARTICIPANT_LISTING'],
      'event_form_element_name' => 'participant_listing_id',
      'class' => 'crm-select2',
      'placeholder' => ts('Disabled'),

    ],
  ],
  'eventsextras_include_map_event_location_default' => [
    'name' => 'eventsextras_include_map_event_location_default',
    'title' => ts('Set Default Include Map to Event Location'),
    'type' => 'Integer',
    'default' => '',
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => '',
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_INFO,
      'parent_setting' => SettingsManager::SETTING_FIELDS['INCLUDE_MAP_LOCATION_EVENT'],
      'event_form_element_name' => 'is_map',
      'class' => '',
    ],
  ],
  'eventsextras_public_event_default' => [
    'name' => 'eventsextras_public_event_default',
    'title' => ts('Set Default Public Event'),
    'type' => 'Integer',
    'default' => 0,
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => '',
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_INFO,
      'parent_setting' => SettingsManager::SETTING_FIELDS['INCLUDE_MAP_PUBLIC_EVENT'],
      'event_form_element_name' => 'is_public',
      'class' => '',
    ],
  ],
  'eventsextras_currency_default' => [
    'name' => 'eventsextras_currency_default',
    'title' => ts('Set Default Currency'),
    'type' => 'String',
    'quick_form_type' => 'Select',
    'default' => '',
    'html_type' => 'select',
    'pseudoconstant' => [
      'optionGroupName' => 'currencies_enabled',
    ],
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => FALSE,
    'description' => ts('Select the currency to be used for event registration.'),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_FEE,
      'parent_setting' => SettingsManager::SETTING_FIELDS['CURRENCY'],
      'event_form_element_name' => 'currency',
      'class' => 'crm-select2',
      'placeholder' => ts('--Select--'),
    ],
  ],
  'eventsextras_payment_processor_selection_default' => [
    'name' => 'eventsextras_payment_processor_selection_default',
    'title' => ts('Set Default Payment Processor Selection'),
    'type' => 'String',
    'quick_form_type' => 'Checkboxes',
    'default' => '',
    'html_type' => 'checkboxes',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => FALSE,
    'description' => ts('
      If this is a paid event and you want users to be able to register and pay online,
      select a payment processor to use. NOTE: Alternatively,
      you can enable the Pay Later feature below without setting up a payment processor.
      All users will then be asked to submit payment offline
      (e.g. mail in a check, call in a credit card, etc.).
      <a href="https://docs.civicrm.org/user/en/stable/contributions/payment-processors"
      target="_blank" class="crm-doc-link no-popup" title="Opens documentation in a new window.">
      (learn more...)
      </a>'),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_FEE,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PAYMENT_PROCESSOR_SELECTION'],
      'event_form_element_name' => 'payment_processor',
      'class' => '',
    ],
  ],
  'eventsextras_enable_pay_later_option_default' => [
    'name' => 'eventsextras_enable_pay_later_option_default',
    'title' => ts('Enable Default Pay Later option?'),
    'type' => 'Integer',
    'default' => '',
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => FALSE,
    'description' => ts('Check this box if you want to give users the option to submit payment offline (e.g. mail in a check, call in a credit card, etc.). '),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_FEE,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PAY_LATER_OPTION'],
      'event_form_element_name' => 'is_pay_later',
      'class' => '',
    ],
  ],
  'eventsextras_enable_pay_later_option_default_label' => [
    'name' => 'eventsextras_enable_pay_later_option_default_label',
    'title' => ts('Set Default Pay Later Label'),
    'type' => 'String',
    'default' => '',
    'html_type' => 'textarea',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => FALSE,
    'description' => ts('Text displayed next to the checkbox for the "pay later" option on the contribution form. You may include HTML formatting tags.'),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_FEE,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PAY_LATER_OPTION'],
      'event_form_element_name' => 'pay_later_text',
      'class' => '',
    ],
  ],
  'eventsextras_enable_pay_later_option_default_instruction' => [
    'name' => 'eventsextras_enable_pay_later_option_default_instruction',
    'title' => ts('Set Default Pay Later Instruction'),
    'type' => 'String',
    'default' => '',
    'html_type' => 'textarea',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => FALSE,
    'description' => ts('Instructions added to Confirmation and Thank-you pages when the user selects the "pay later" option (e.g. "Mail your check to ... within 3 business days.").  '),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_FEE,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PAY_LATER_OPTION'],
      'event_form_element_name' => 'pay_later_receipt',
      'class' => '',
    ],
  ],
  'eventsextras_enable_pay_later_option_default_billing_address_required' => [
    'name' => 'eventsextras_enable_pay_later_option_default_billing_address_required',
    'title' => ts('Set Default Billing Address Required?'),
    'type' => 'Integer',
    'default' => '',
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => FALSE,
    'description' => ts('Check this box to require users who select the pay later option to provide billing name and address.'),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_FEE,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PAY_LATER_OPTION'],
      'event_form_element_name' => 'is_billing_required',
      'class' => '',
    ],
  ],
  'eventsextras_pending_participant_expiration_default' => [
    'name' => 'eventsextras_pending_participant_expiration_default',
    'title' => ts('Set Default Pending Participant Expiration'),
    'type' => 'Integer',
    'quick_form_type' => 'Text',
    'default' => '',
    'html_type' => 'text',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => ts(''),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_REGISTRATION,
      'parent_setting' => SettingsManager::SETTING_FIELDS['PENDING_PARTICIPANT_EXPIRATION'],
      'event_form_element_name' => 'expiration_time',
      'class' => '',
    ],
  ],

  'eventsextras_allow_self_service_default' => [
    'name' => 'eventsextras_allow_self_service_default',
    'title' => ts('Set Default Allow Self-Service Cancellation or Transfer?'),
    'type' => 'Integer',
    'quick_form_type' => 'Checkbox',
    'default' => '',
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => ts(''),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_REGISTRATION,
      'parent_setting' => SettingsManager::SETTING_FIELDS['ALLOW_SELF_SERVICE'],
      'event_form_element_name' => 'allow_selfcancelxfer',
    ],
  ],
  'eventsextras_allow_self_service_default_time_limit' => [
    'name' => 'eventsextras_allow_self_service_default_time_limit',
    'title' => ts('Set Default Cancellation or transfer time limit (hours)	'),
    'type' => 'Integer',
    'quick_form_type' => 'Text',
    'default' => '',
    'html_type' => 'text',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => ts(''),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_REGISTRATION,
      'parent_setting' => SettingsManager::SETTING_FIELDS['ALLOW_SELF_SERVICE'],
      'event_form_element_name' => 'selfcancelxfer_time',
    ],
  ],
  'eventsextras_register_multiple_participants_default' => [
    'name' => 'eventsextras_register_multiple_participants_default',
    'title' => ts('Set Default Register multiple participants?	'),
    'type' => 'Integer',
    'quick_form_type' => 'Checkbox',
    'default' => '',
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => ts(''),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_REGISTRATION,
      'parent_setting' => SettingsManager::SETTING_FIELDS['REGISTER_MULTIPLE_PARTICIPANTS'],
      'event_form_element_name' => 'is_multiple_registrations',
    ],
  ],
  'eventsextras_register_multiple_participants_default_maximum_participant' => [
    'name' => 'eventsextras_register_multiple_participants_default_maximum_participant',
    'title' => ts('Set Default Maximum additional participants	'),
    'type' => 'Integer',
    'quick_form_type' => 'Select',
    'default' => 9,
    'html_type' => 'select',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => ts(''),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_REGISTRATION,
      'parent_setting' => SettingsManager::SETTING_FIELDS['REGISTER_MULTIPLE_PARTICIPANTS'],
      'event_form_element_name' => 'max_additional_participants',
    ],
  ],
  'eventsextras_register_multiple_participants_allow_same_participant_emails_default' => [
    'name' => 'eventsextras_register_multiple_participants_allow_same_participant_emails_default',
    'title' => ts('Set Default Same email address?	'),
    'type' => 'Integer',
    'quick_form_type' => 'Checkbox',
    'default' => '',
    'html_type' => 'checkbox',
    'add' => '1.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'is_help' => TRUE,
    'description' => ts(''),
    'help_text' => '',
    'extra_attributes' => [
      'section' => SettingsManager::EVENT_REGISTRATION,
      'parent_setting' => SettingsManager::SETTING_FIELDS['REGISTER_MULTIPLE_PARTICIPANTS'],
      'event_form_element_name' => 'allow_same_participant_emails',
    ],
  ],
];
